#!/bin/bash

osname=jasonwnix

die () {
    printf "$1\n" && exit 1
}

isoboot () {
    # Note: The 512 byte bootsector limit doesn't seem to apply to the iso,
    # but we'll obey it anyway so floppy and iso work equally well.
    isodir=isodir
    rm -rf "$isodir" && mkdir -p "$isodir" && cp "$osname" "$isodir" &&
    mkisofs -no-emul-boot -input-charset=utf8 \
        -o "$osname.iso" -b "$osname" "$isodir/"
    qemu-system-x86_64 -cdrom "$osname.iso"
    rm -rf "$osname.iso" "$isodir"
}

flpboot () {
    qemu-system-x86_64 "$osname"
}


rm -f *.bin *.flp *.iso
make
isoboot
flpboot
make clean
